apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: d29yZHByZXNzcGFzcw==
  mysql-user: d29yZHByZXNz
  mysql-password: d29yZHByZXNzcGFzcw==
  mysql-database: d29yZHByZXNz