apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cmV0by0yLXRldA==
  mysql-user: d29yZHByZXNz
  mysql-password: cmV0by0yLXRldA==
  mysql-database: d29yZHByZXNz