apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wordpress-cert
  namespace: default
spec:
  secretName: wordpress-tls
  issuerRef:
    name: selfsigned-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - a9af193cdc5e6413bba9a8d59a22ea0d-1193761687.us-east-1.elb.amazonaws.com
